config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy] do
      collection do
        get 'search'
      end
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show", as: "customer"
    get "customers/infomation/edit" => "customers#edit", as: "edit_public_customer"
    patch "customers/infomation" => "customers#update", as: "update_public_customer"
    get "customers/delete_confirm" => "customers#delete_confirm"
    patch "customers/delete" => "customers#delete_process"
    resources :addresses, except: [:new, :show]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    post "orders/confirmed" => "orders#confirmed"
    resources :orders, only: [:new, :index, :show]
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
    end
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :first_name_kana, presence: true
    validates :last_name_kana, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :telephone_number, presence: true

    def full_name
      self.last_name + " " + self.first_name
    end

    def customer_address_display
      '〒' + postal_code + ' ' + address + ' ' + full_name
    end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を編集しました。"
      redirect_to admin_customers_path
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12 p-0">
      <h5 class="d-inline-block bg-light col-2 text-center my-5 text-nowrap">商品編集</h5>
    </div>
  </div>
  <div class="row justify-content-around">
    <% if @customer.errors.any? %>
    <div>
      <h2><%= pluralize(@customer.errors.count, "error") %> 件のエラーがあります。</h2>
      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <div class="col-sm-10 p-0">
      <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
        <div class="form-group row justify-content-flex-start">
          <div class="col-2 col-form-label">
            <label　for= "id">会員ID</label>
          </div>
          <div class="col-3 flex-row">
            <%= @customer.id %>
          </div>
        </div>
        
        <div class="form-group row justify-content-flex-start">
          <div class="col-2 col-form-label">
            <label for="name">氏名</label>
          </div>
          <div class="col-3 mr-4 form-inline">
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "令和", class: "form-control border border-secondary rounded" %>
          </div>
          <div class="col-3 form-inline">
            <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "道子", class: "form-control border border-secondary rounded" %>
          </div>
        </div>
        
        <div class="form-group row justify-content-flex-start">
          <div class="col-2 col-form-label">
            <label for="name_kana">フリガナ</label>
          </div>
          <div class="col-3 mr-4 form-inline">
            <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", placeholder: "レイワ", class: "form-control border border-secondary rounded" %>
          </div>
          <div class="col-3 form-inline">
            <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", placeholder: "ミチコ", class: "form-control border border-secondary rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-flex-start">
          <div class="col-2 col-form-label">
            <%= f.label :postal_code, class: "text-nowrap" do %>郵便番号<% end %>
          </div>
          <div class="col-3 form-inline">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "0000000", class: "form-control border border-secondary rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-flex-start">
          <div class="col-sm-2 col-form-label">
            <%= f.label :address, class: "text-nowrap" do %>住所<% end %>
          </div>
          <div class="col-sm-7 form">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: "東京都渋谷区代々木神園町0-0", class: "form-control border border-secondary rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-flex-start">
          <div class="col-sm-2 col-form-label">
            <%= f.label :telephone_number, class: "text-nowrap" do %>電話番号<% end %>
          </div>
          <div class="col-sm-3 form-inline">
            <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", placeholder: "00000000000", class: "form-control border border-secondary rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-flex-start">
          <div class="col-sm-2 col-form-label">
            <%= f.label :email, class: "text-nowrap" do %>メールアドレス<% end %>
          </div>
          <div class="col-sm-3 form-inline">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "sample@example.com", class: "form-control border border-secondary rounded" %>
          </div>
        </div>

        <div class="form-group row justify-content-flex-start">
          <div class="col-sm-2 col-form-label">
            <%= f.label :is_deleted, class: "font-weight-bold text-nowrap" do %>会員ステータス<% end %>
          </div>
          <div class="col-sm-3 ">
            <div class="custom-control custom-radio custom-control-inline">
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効", value: true, class: "text-nowrap mr-5" %>

              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会", value: false, class: "text-nowrap" %>
            </div>
          </div>
        </div>
        <div class="form-group row justify-content-flex-start">
          <div class="col-sm-2"></div>
          <div class="actions col-sm-2 col-form-label text-center">
            <%= f.submit "変更を保存", class: "btn btn-success btn-block" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-12 p-0">
      <h5 class="d-inline-block bg-light col-2 text-center my-5 text-nowrap">会員一覧</h5>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-10 mx-auto">
      <table class="table">
        <thead class="thead-light">
          <tr class="text-nowrap">
            <th scope="col-1">会員ID</th>
            <th scope="col-2">氏名</th>
            <th scope="col-2">メールアドレス</th>
            <th scope="col-2">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr class="table">
              <td class="col-1"><%= customer.id %></td>
              <td class="col-2 text-nowrap"><%= link_to customer.full_name, admin_customer_path(customer.id), style: "text-decoration: underline; color: black" %></td>
              <td class="col-2"><%= customer.email %></td>
              <td class="col-2">
                <% if customer.is_deleted? %>
                  <P class="font-weight-bold", style="color-grey">退会</P>
                <% else %>
                  <P class="font-weight-bold", style="color:lightgreen">有効</P>
                <% end %>
              </td>
            </tr>
          <% end %>
          <%= paginate @customers %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h5 class="d-inline-block bg-light col-2 text-center my-5 text-nowrap"><%= @customer.full_name %>さんの会員詳細</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 text-left">
      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">会員ID</label>
        <div class="col-sm-6"><%= @customer.id %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">氏名</label>
        <div class="col-sm-6"><%= @customer.last_name %>　<%= @customer.first_name %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">フリガナ</label>
        <div class="col-sm-6"><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></div></br>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">郵便番号</label>
        <div class="col-sm-6"><%= @customer.postal_code %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">住所</label>
        <div class="col-sm-6"><%= @customer.address %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">電話番号</label>
        <div class="col-sm-6"><%= @customer.telephone_number %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">メールアドレス</label>
        <div class="col-sm-6"><%= @customer.email %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">会員ステータス</label>
        <div class="col-sm-6">
          <% if @customer.is_deleted? %>
            <P class="font-weight-bold", style="color-grey">退会</P>
          <% else %>
            <P class="font-weight-bold", style="color:lightgreen">有効</P>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-2 text-center text-nowrap mr-5">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success btn-block" %>
    </div>
    <div class="col-sm-3 text-center text-nowrap">
      <%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer.id), class: "btn btn-primary btn-block" %>
    </div>
  </div>
</div>