config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy] do
      collection do
        get 'search'
      end
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show", as: "customer"
    get "customers/infomation/edit" => "customers#edit", as: "edit_public_customer"
    patch "customers/infomation" => "customers#update", as: "update_public_customer"
    get "customers/delete_confirm" => "customers#delete_confirm"
    patch "customers/delete" => "customers#delete_process"
    resources :addresses, except: [:new, :show]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    post "orders/confirmed" => "orders#confirmed"
    resources :orders, only: [:new, :index, :show]
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
    end
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_the_making: 2, shipping_preparation: 3, completed: 4 }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order_details = order.order_details
    order.update(order_params)
    flash[:notice] = "ステータスを変更しました。"
    if order.status == "payment_confirmation"
      order_details.update_all(making_status: "waiting_for_making")
      flash[:notice] = "入金を確認しました。制作の準備をしてください。"
    end
    redirect_to admin_order_path(order.id)
  end

private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h5 class="d-inline-block bg-light col-2 text-center my-5 text-nowrap">注文履歴詳細</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 text-left">
      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">購入者</label>
        <div class="col-sm-6"><%= link_to @order.customer.full_name, admin_customer_path(@order.customer.id), style: "text-decoration: underline; color: black;" %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">注文日</label>
        <div class="col-sm-6"><%= @order.created_at.strftime('%Y/%m/%d') %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">配送先</label>
        <div class="col-sm-6"><%= @order.address_display %></div></br>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">支払方法</label>
        <div class="col-sm-6"><%= @order.payment_method_i18n %></div>
      </div>

      <div class="d-flex flex-row mb-2">
        <label class="col-sm-3">注文ステータス</label>
        <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: :true, class: "d-flex flex-row align-items-center mb-2 col-sm-5" do |f| %>
          <div>
            <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, class: "col-sm-3 form-control border border-secondary" %>
          </div>
          <div class="actions col-sm-2">
            <%= f.submit "更新", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9">
      <table class="table">
        <thead class="thead-light">
          <tr class="text-nowrap">
            <tr class="text-nowrap">
            <th scope="col-sm-3">商品</th>
            <th scope="col-sm-1">単価(税込)</th>
            <th scope="col-sm-1">個数</th>
            <th scope="col-sm-1">小計</th>
            <th scope="col-sm-3">制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr class="table">
              <td class="col-sm-3"><%= order_detail.item.name %></td>
              <td class="col-sm-1 text-nowrap"><%= order_detail.price.to_s(:delimited) %></td>
              <td class="col-sm-1"><%= order_detail.amount %></td>
              <td class="col-sm-1"><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
              <td class="col-sm-3">
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: :true, class: "d-flex flex-row align-items-center mb-2" do |f| %>
                  <div>
                    <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, class: "form-control border border-secondary" %>
                  </div>
                  <div class="actions col-sm-1">
                    <%= f.submit "更新", class: "btn btn-success" %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tr class="text-nowrap">
          <th class="font-weight-bold">商品合計</td>
          <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr class="text-nowrap">
          <th class="font-weight-bold">配送料</td>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr class="text-nowrap">
          <th class="font-weight-bold">請求金額</td>
          <td><%= (@order.total_payment).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>