config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy] do
      collection do
        get 'search'
      end
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show", as: "customer"
    get "customers/infomation/edit" => "customers#edit", as: "edit_public_customer"
    patch "customers/infomation" => "customers#update", as: "update_public_customer"
    get "customers/delete_confirm" => "customers#delete_confirm"
    patch "customers/delete" => "customers#delete_process"
    resources :addresses, except: [:new, :show]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    post "orders/confirmed" => "orders#confirmed"
    resources :orders, only: [:new, :index, :show]
    resources :items, only: [:index, :show] do
      collection do
        get 'search'
      end
    end
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :customer

  validates :amount, presence: true
  validates :item_id, presence: true
  validates :customer_id, presence: true

  def with_tax_price
    (item.price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :first_name_kana, presence: true
    validates :last_name_kana, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :telephone_number, presence: true

    def full_name
      self.last_name + " " + self.first_name
    end

    def customer_address_display
      '〒' + postal_code + ' ' + address + ' ' + full_name
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_the_making: 2, shipping_preparation: 3, completed: 4 }

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { cannot_make: 0, waiting_for_making: 1, in_the_making: 2, completed: 3 }

  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = Order.page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]

  def search
    @results = @q.result
  end

  def index
    if params[:q]
      @results = @q.result
      @items = @q.result.page(params[:page])
    else
      @items = Item.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新しい商品を登録しました。"
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を編集しました。"
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  private

  def set_q
    @q = Item.ransack(params[:q])
  end

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @q = Item.ransack(params[:q])
    @items = @q.result.where(is_active: true).page(params[:page]).per(8)
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :Customer
      top_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/shared/_search.html.erb
<%= search_form_for(q, url:admin_items_path) do |f| %>
  <div class="input-group">
    <%= f.text_field :name_cont, placeholder: "search", class: "form-control" %>
    <span class="input-group-btn">
      <%= button_tag type: "submit", class: "btn btn-outline-secondary" do %>
        <i class="fas fa-search"></i>
      <% end %>
    </span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
          <%= link_to NaganoCake, root_path, class: "navbar-brand col-sm-3" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="row">
            <div class="collapse navbar-collapse " id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto d-flex justify-content-end col-sm">
                <% if customer_signed_in? %>
                  <li class="nav-link text-light">
                    <%= link_to customer_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">マイページ</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to items_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">商品一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to cart_items_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">カート</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to destroy_customer_session_path, method: :delete, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">ログアウト</button>
                    <% end %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-link text-light">
                    <%= link_to admin_items_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">商品一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to admin_customers_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">会員一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to admin_root_path, class: "header-button" do %>
                      <button type="button" class=" btn btn-outline-secondary">注文履歴一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to admin_genres_path, class: "header-button" do %>
                      <button type="button" class="btn btn-outline-secondary">ジャンル一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to destroy_admin_session_path, method: :delete, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">ログアウト</button>
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-link text-light">
                    <%= link_to about_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">About</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to items_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">商品一覧</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to new_customer_registration_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">新規登録</button>
                    <% end %>
                  </li>
                  <li class="nav-link text-light">
                    <%= link_to new_customer_session_path, class: "header-button" do %>
                      <button type="button" class="text-nowrap btn btn-outline-secondary">ログイン</button>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="row d-flex justify-content-end col-sm-12 mx-0">
              <% if admin_signed_in? %>
                <%= render "admin/shared/search", q: @q %>
              <% elsif customer_signed_in? %>
                <div class="col-sm-4"><p class="text-left text-nowrap">ようこそ、<%= current_customer.last_name %>さん！</p></div>
                <div class="col-sm-1"></div>
                <div class="col-sm-5">
                  <%= render "public/shared/search", q: @q %>
                </div>
              <% else %>
                <%= render "public/shared/search", q: @q %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="mt-5 bg-light vh-100">
        <div class="row mx-auto">
          <div class="mx-auto mt-2">
            <P>Copyright © Infratop Inc. All Rights Reserved.</P>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>